### ISSUE TITLE
Transition classes and events  are not applied in correct order on Firefox

### ISSUE THREAD

**Issue by fabien-ml** [solidjs-community/solid-transition-group#12]
Hi, looks like classes and events are not applied in correct order on Firefox.
I'm using Firefox 98.0.1 on MacOS 11.6.

Here is an example project.
Run it on Firefox and click on the button, the "enter" transition doesn't works and events are not called in correct order.

Chrome and Safari works fine.

[bug-transition-firefox.zip](https://github.com/solidjs/solid-transition-group/files/8252288/bug-transition-firefox.zip)

**Comment by fabien-ml** [comment]
@ryansolid any plan on publishing a new version of this package ?

**Comment by ryansolid** [comment]
Ok this got lost in my notifications. Published 0.0.9.

**Comment by ryansolid** [comment]
Hmm.. something in the last 2 PRs broke my Custom example here: https://codesandbox.io/s/basic-css-transition-36rln?file=/package.json.

**Comment by thetarnav** [comment]
@kirpalmakanga calling the enter transition two frames after instead of one works great for animating using classes ([demo](https://playground.solidjs.com/anonymous/d0ddef95-e3bc-4213-b2f1-27318992958b)), but when using events and js animations the callback is fired too late, causing the entering element to be visible with its normal styles for one frame before the animation is run ([demo](https://playground.solidjs.com/anonymous/5ea43307-1697-454a-bfb6-a8bb3ed269df)).
Do you think there is a possibility to apply classes as it is done currently, but schedule the `onEnter` callback with a microtask instead? This way it will be executed as soon as it is added to the DOM.

**Comment by thetarnav** [comment]
Published `0.1.1` that should hopefully work well with js events and CSS classes.
